import "./globals.css"
import i18nConfig from "@/i18nConfig"
import { AntdRegistry } from "@ant-design/nextjs-registry"
import { ConfigProvider } from "antd"
import theme from "@/theme/themeConfig"
import { Inter } from "next/font/google"
import { dir } from "i18next"

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
  title: "iGPSPORT迹驰",
  description: "Generated by Next.js",
  icons: {
    icon: "/logo.ico",
  },
}

export function generateStaticParams() {
  return i18nConfig.locales.map((locale) => ({ locale }))
}

export default function RootLayout({ children, params: { locale } }) {
  return (
    <html lang={locale} dir={dir(locale)}>
      <body className={inter.className}>
        <AntdRegistry>
          <ConfigProvider theme={theme}>
            <main className="mt-[64px] select-none">{children}</main>
          </ConfigProvider>
        </AntdRegistry>
      </body>
    </html>
  )
}
