import Navbar from "@/components/Navbar"
import "./globals.css"
import Footer from "@/components/Footer"
import TranslationsProvider from "@/components/TranslationsProvider"
import initTranslations from "../i18n"
import { AntdRegistry } from "@ant-design/nextjs-registry"
import { ConfigProvider } from "antd"
import theme from "@/theme/themeConfig"

export const metadata = {
  title: "齐物科技",
  description: "Generated by Next.js",
  icons: {
    icon: "/logo.ico",
  },
}

const i18nNamespaces = ["default"]

export default async function RootLayout({ children, params: { locale } }) {
  const { t, resources } = await initTranslations(locale, i18nNamespaces)
  return (
    <html>
      <body>
        <TranslationsProvider
          resources={resources}
          locale={locale}
          namespaces={i18nNamespaces}
        >
          <AntdRegistry>
            <ConfigProvider theme={theme}>
              <Navbar />
              <main className="mt-[64px]">{children}</main>
              <Footer />
            </ConfigProvider>
          </AntdRegistry>
        </TranslationsProvider>
      </body>
    </html>
  )
}
